# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 4) do

  create_table "polls", :force => true do |t|
    t.column "created_at",  :datetime
    t.column "description", :text
  end

  add_index "polls", ["created_at"], :name => "index_polls_on_created_at"

  create_table "questions", :force => true do |t|
    t.column "description", :text
    t.column "poll_id",     :integer, :null => false
  end

  add_index "questions", ["poll_id"], :name => "fk_question_polls"

  create_table "votes", :force => true do |t|
    t.column "rate",        :integer
    t.column "question_id", :integer, :null => false
  end

  add_index "votes", ["question_id"], :name => "fk_vote_questions"

end
